[engine]
name = "Curloz Engine"
version_major = 0
version_minor = 1
version_patch = 0

[window]
width = 800
height = 600
vsync = false
refreshrate = 120
triplebuffering = true

[entity]
# Entity file. Has to be a JSON. Mention the path here.
file = "config/entity.json"